2021-05-19 22:20:36,177 INFO    MainThread:14090 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 22:20:36,177 INFO    MainThread:14090 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 22:20:36,177 INFO    MainThread:14090 [wandb_init.py:_log_setup():336] Logging user logs to /home/kukjin/Study/RL/소프트웨어 융합 캡스톤 디자인/ApexDQFD/wandb/run-20210519_222036-2c9fuh72/logs/debug.log
2021-05-19 22:20:36,177 INFO    MainThread:14090 [wandb_init.py:_log_setup():337] Logging internal logs to /home/kukjin/Study/RL/소프트웨어 융합 캡스톤 디자인/ApexDQFD/wandb/run-20210519_222036-2c9fuh72/logs/debug-internal.log
2021-05-19 22:20:36,178 INFO    MainThread:14090 [wandb_init.py:init():369] calling init triggers
2021-05-19 22:20:36,178 INFO    MainThread:14090 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 22:20:36,178 INFO    MainThread:14090 [wandb_init.py:init():391] re-initializing run, found existing run on stack: m006lfu8
2021-05-19 22:20:36,179 INFO    MainThread:14090 [wandb_run.py:finish():1167] finishing run neverparadise/apex_dqfd/m006lfu8
2021-05-19 22:20:36,180 INFO    MainThread:14090 [jupyter.py:save_history():320] not saving jupyter history
2021-05-19 22:20:36,180 INFO    MainThread:14090 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 22:20:36,180 INFO    MainThread:14090 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-19 22:20:36,180 INFO    MainThread:14090 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-05-19 22:20:36,180 INFO    MainThread:14090 [wandb_run.py:_restore():1466] restore
2021-05-19 22:20:36,509 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 762
  total_bytes: 762
}

2021-05-19 22:20:36,941 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 762
  total_bytes: 5124
}

2021-05-19 22:20:37,355 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5124
  total_bytes: 5124
}

2021-05-19 22:20:37,457 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5124
  total_bytes: 5124
}

2021-05-19 22:20:37,558 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5124
  total_bytes: 5124
}

2021-05-19 22:20:37,660 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5124
  total_bytes: 5124
}

2021-05-19 22:20:37,761 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5124
  total_bytes: 5124
}

2021-05-19 22:20:37,861 INFO    MainThread:14090 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5124
  total_bytes: 5124
}

2021-05-19 22:20:38,927 INFO    MainThread:14090 [wandb_run.py:_show_files():1838] logging synced files
2021-05-19 22:20:38,930 INFO    MainThread:14090 [wandb_init.py:init():418] starting backend
2021-05-19 22:20:38,930 INFO    MainThread:14090 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-19 22:20:38,933 INFO    MainThread:14090 [backend.py:ensure_launched():123] starting backend process...
2021-05-19 22:20:39,036 INFO    MainThread:14090 [backend.py:ensure_launched():128] started backend process with pid: 65235
2021-05-19 22:20:39,037 INFO    MainThread:14090 [wandb_init.py:init():423] backend started and connected
2021-05-19 22:20:39,051 INFO    MainThread:14090 [wandb_init.py:init():465] updated telemetry
2021-05-19 22:20:39,051 INFO    MainThread:14090 [wandb_init.py:init():484] communicating current version
2021-05-19 22:20:44,052 INFO    MainThread:14090 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 22:21:14,052 INFO    MainThread:14090 [interface.py:_communicate_run():642] couldn't get run from backend
2021-05-19 22:21:14,052 ERROR   MainThread:14090 [wandb_init.py:init():501] backend process timed out
2021-05-19 22:21:14,052 ERROR   MainThread:14090 [wandb_init.py:init():510] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-05-19 22:21:19,074 INFO    MainThread:14090 [wandb_init.py:teardown():187] tearing down wandb.init
